// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultipleDbApp.Data;

#nullable disable

namespace MultipleDbApp.Migrations.SecondaryAppDb
{
    [DbContext(typeof(SecondaryAppDbContext))]
    [Migration("20240122094653_initial-migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");
#pragma warning restore 612, 618
        }
    }
}
